#!/usr/bin/env bash
# Provision a server for an EXISTING unit type (one unit per server). This is an
# OPERATOR task — the unit's Go code must already exist. To author a brand-new
# protocol's code first, use scripts/new-gateway.sh.
#
#   scripts/provision-server.sh <unit> [--no-build]
#
# It:
#   1. builds the lean image device-gateway-<unit> (only that unit compiles in —
#      a GPS-only unit carries no video/ffmpeg-driven code paths),
#   2. writes deploy/docker-compose.<unit>.yml — a full single-unit stack
#      (Postgres + the unit gateway + admin),
#   3. writes deploy/.env from deploy/.env.example if it doesn't exist yet.
#
# Then: edit deploy/.env (secrets, webhook, MEDIA_ADVERTISE_HOST) and run
#   docker compose -f deploy/docker-compose.<unit>.yml --env-file deploy/.env up -d --build
#
# NOTE: deploy/docker-compose.yml is the *multi-unit* stack (one process hosting
# every registered unit, used for dev / a single combined box). This script is
# the opposite model: one lean process per unit, isolated per server.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNIT="${1:-}"
BUILD=1
[[ "${2:-}" == "--no-build" ]] && BUILD=0

if [[ -z "$UNIT" ]]; then
  echo "usage: scripts/provision-server.sh <unit> [--no-build]" >&2
  exit 1
fi
if [[ ! "$UNIT" =~ ^[a-z][a-z0-9_]*$ ]]; then
  echo "error: unit name must be lowercase [a-z0-9_], starting with a letter" >&2
  exit 1
fi
# Provisioning != scaffolding: the unit's code must already exist.
if [[ ! -d "$ROOT/cmd/$UNIT" ]]; then
  echo "error: cmd/$UNIT not found — this unit has no code yet." >&2
  echo "       Scaffold it first:  scripts/new-gateway.sh $UNIT" >&2
  exit 1
fi

UNIT_UPPER="$(printf '%s' "$UNIT" | tr '[:lower:]' '[:upper:]')"

# The conventional device port for known units (matches each unit's
# DefaultDevicePort() in Go). New/unknown units fall back to 33000 — the operator
# can override with DEVICE_PORT in deploy/.env. Whatever value wins is used for
# BOTH the in-container listen port and the published host port, so they always
# agree.
case "$UNIT" in
  howen)    DEFAULT_DEVICE_PORT=33000 ;;
  fleetiger) DEFAULT_DEVICE_PORT=8050 ;;
  cathexis) DEFAULT_DEVICE_PORT=33010 ;;
  navtelecom) DEFAULT_DEVICE_PORT=4000 ;;
  jt808)    DEFAULT_DEVICE_PORT=6608 ;;
  *)        DEFAULT_DEVICE_PORT=33000 ;;
esac

COMPOSE_OUT="$ROOT/deploy/docker-compose.$UNIT.yml"
ENV_OUT="$ROOT/deploy/.env"

# Single-unit stack. Unlike the multi-unit deploy/docker-compose.yml, this builds
# the lean device-gateway-<unit> image and exposes only that unit's ports. The
# device port is driven by one knob (DEVICE_PORT) wired to both <UNIT>_PORT inside
# the container and the published port, so they can never drift apart.
if [[ -e "$COMPOSE_OUT" ]]; then
  echo "keeping existing $COMPOSE_OUT"
else
  sed -e "s/__UNIT__/$UNIT/g" \
      -e "s/__UNIT_UPPER__/$UNIT_UPPER/g" \
      -e "s/__DEVICE_PORT__/$DEFAULT_DEVICE_PORT/g" \
      > "$COMPOSE_OUT" <<'YAML'
# Single-unit gateway stack for '__UNIT__', generated by scripts/provision-server.sh.
# One lean gateway process (only __UNIT__ compiled in) behind one Postgres
# registry, telemetry webhook, HTTP API, and admin panel.
services:
  postgres:
    image: postgres:16-alpine
    container_name: device-gateway-__UNIT__-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gateway}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-gateway}
      - POSTGRES_DB=${POSTGRES_DB:-gateway}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-gateway} -d ${POSTGRES_DB:-gateway}"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  gateway:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
      args:
        UNIT: __UNIT__
    image: device-gateway-__UNIT__:latest
    container_name: device-gateway-__UNIT__
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GATEWAY=${GATEWAY:-__UNIT__.example.net}
      - LISTEN_HOST=0.0.0.0
      # Device TCP port. One knob (DEVICE_PORT) drives the listen port and the
      # published port below so they always match. Default __DEVICE_PORT__.
      - __UNIT_UPPER___PORT=${DEVICE_PORT:-__DEVICE_PORT__}
      # Management/control HTTP API (API-key protected). 0 disables.
      - HTTP_PORT=${HTTP_PORT:-8080}
      # Shared secret the admin panel uses to authenticate. Same value as the
      # admin's GATEWAY_API_TOKEN.
      - INTERNAL_API_TOKEN=${ADMIN_API_TOKEN:-}
      # Telemetry sink: the universal-JSON endpoint that stores all GPS/event data.
      - DEVICE_WEBHOOK_URL=${DEVICE_WEBHOOK_URL:-}
      # Gateway's own DB — device-verification registry + per-unit settings/mappings.
      - DATABASE_URL=postgres://${POSTGRES_USER:-gateway}:${POSTGRES_PASSWORD:-gateway}@postgres:5432/${POSTGRES_DB:-gateway}?sslmode=disable
      - DEVICE_AUTH_MODE=${DEVICE_AUTH_MODE:-postgres}
      - DEVICE_REJECT_UNKNOWN=${DEVICE_REJECT_UNKNOWN:-true}
      - MAPPING_REFRESH_SECONDS=${MAPPING_REFRESH_SECONDS:-60}
      # Live video (HLS) — video-capable units only. MEDIA_ADVERTISE_HOST is the
      # host devices dial back for media frames (no port); empty DISABLES video.
      - MEDIA_ADVERTISE_HOST=${MEDIA_ADVERTISE_HOST:-}
      - MEDIA_PORT=${MEDIA_PORT:-33001}
      - CLIPS_ROOT=${CLIPS_ROOT:-/var/lib/gateway/clips}
      # Scheduled gateway-DB backups (schedule/retention editable live in the admin).
      - BACKUPS_ROOT=${BACKUPS_ROOT:-/var/lib/gateway/backups}
      - BACKUP_ENABLED=${BACKUP_ENABLED:-true}
      - BACKUP_TIME=${BACKUP_TIME:-02:00}
      - BACKUP_RETENTION=${BACKUP_RETENTION:-7}
      # Device local-clock offset fallback (a unit's own settings override it).
      - DEVICE_TZ_OFFSET=${DEVICE_TZ_OFFSET:-0}
      # Set DEBUG=1 (or DEBUG=tcp/__UNIT__) for verbose per-frame logging.
      - DEBUG=${DEBUG:-}
    volumes:
      - clipdata:/var/lib/gateway/clips
      - backupdata:/var/lib/gateway/backups
    ports:
      - "${DEVICE_PORT:-__DEVICE_PORT__}:${DEVICE_PORT:-__DEVICE_PORT__}"  # device control
      - "${MEDIA_PORT:-33001}:${MEDIA_PORT:-33001}"  # media (video units only)
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"  # HTTP API
    restart: unless-stopped

  # Admin panel (Next.js). Talks to the gateway ONLY over its HTTP API, using a
  # server-held API key — it has no database access of its own.
  admin:
    build:
      context: ../admin
      dockerfile: Dockerfile
    image: device-gateway-admin:latest
    container_name: device-gateway-__UNIT__-admin
    depends_on:
      - gateway
    environment:
      - GATEWAY_URL=http://gateway:8080
      - GATEWAY_API_TOKEN=${ADMIN_API_TOKEN:?set ADMIN_API_TOKEN in your .env}
      - SESSION_SECRET=${SESSION_SECRET:?set SESSION_SECRET in your .env}
      - SESSION_TTL_HOURS=${SESSION_TTL_HOURS:-12}
      - SESSION_COOKIE_SECURE=${SESSION_COOKIE_SECURE:-true}
      - NODE_ENV=production
    ports:
      - "${ADMIN_PORT:-3000}:3000"
    restart: unless-stopped

volumes:
  pgdata:
  clipdata:
  backupdata:
YAML
  echo "wrote deploy/docker-compose.$UNIT.yml"
fi

if [[ -e "$ENV_OUT" ]]; then
  echo "keeping existing deploy/.env"
elif [[ -e "$ROOT/deploy/.env.example" ]]; then
  cp "$ROOT/deploy/.env.example" "$ENV_OUT"
  echo "wrote deploy/.env (from .env.example — fill in secrets before running)"
fi

if [[ "$BUILD" == "1" ]]; then
  echo "building lean image device-gateway-$UNIT ..."
  docker build -f "$ROOT/deploy/Dockerfile" --build-arg UNIT="$UNIT" \
    -t "device-gateway-$UNIT" "$ROOT"
fi

cat <<EOF

Provisioned '$UNIT'. Next:
  1. Edit deploy/.env — ADMIN_API_TOKEN, SESSION_SECRET, DEVICE_WEBHOOK_URL,
     and (only for video units) MEDIA_ADVERTISE_HOST.
     Device port defaults to $DEFAULT_DEVICE_PORT; set DEVICE_PORT in deploy/.env to change it.
  2. Start the stack:
       docker compose -f deploy/docker-compose.$UNIT.yml --env-file deploy/.env up -d --build
EOF
